# Github: https://github.com/louislam/uptime-kuma/blob/1.23.X/docker/docker-compose.yml

version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - /opt/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    restart: always
